[package]
name = "doomsday"
version = "0.1.0"
authors = ["Nathan Lilienthal <nathan@nixpulvis.com>"]
edition = "2018"
description = "An implementation of Conway's doomsday algorithm."
documentation = "https://docs.rs/doomsday"
license = "Beerware"
